services:
    apache:
        container_name: armorcms-apache
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        user: 1000:1000
        ports:
            - 8080:80
        depends_on:
            - mysql
        volumes:
            - ./../:/var/www/html/
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        networks:
            - web

    mysql:
        container_name: armorcms-mysql
        image: mysql:${MYSQL_VERSION}
        volumes:
            - database-volume:/var/lib/mysql:rw
        command:
            - "--default-authentication-plugin=mysql_native_password"
        env_file:
            - .env
        ports:
            - 3306:3306
        networks:
            - web

volumes:
    database-volume:

networks:
    web: