services:
    apache:
        container_name: armorcms-apache
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        ports:
            - 8080:80
        depends_on:
            mysql:
                condition: service_healthy
        volumes:
            - ./../:/var/www/html:rw
        networks:
            - armorcms-network

    mysql:
        container_name: armorcms-mysql
        image: mysql:${MYSQL_VERSION}
        volumes:
            - database-volume:/var/lib/mysql:rw
        command:
            - "--default-authentication-plugin=mysql_native_password"
        env_file:
            - .env
        ports:
            - 3306:3306
        networks:
            - armorcms-network
        healthcheck:
            test: "/usr/bin/mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD --execute \"SHOW DATABASES;\""
            interval: 2s
            timeout: 20s
            retries: 10

volumes:
    database-volume:

networks:
    armorcms-network: