services:
    php-apache:
        build:
            context: "../"
            dockerfile: "./docker-apache/Dockerfile"
        ports:
            - "8080:80"
        depends_on:
            - "mysql"
        volumes:
            - "./../:/var/www/html/"
            - "./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
        networks:
            - web

    mysql:
        image: mysql:${MYSQL_VERSION}
        # Uncomment line below if you are using a Mac with the M1 chip
        #platform: linux/amd64
        volumes:
            #- "./mysql_seed.sql:/docker-entrypoint-initdb.d/mysql_seed.sql"
#            - "./dbdata:/var/lib/mysql"
            - database-volume:/var/lib/mysql:rw
        command:
            - "--default-authentication-plugin=mysql_native_password"
        env_file:
            - .env
        networks:
            - web

volumes:
    database-volume:

networks:
    web: