# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    default_locale: 'pl_PL'
    translatable_locale: 'pl_PL'
    supported_locales: ['pl_PL', 'en_US']
    user_avatar_directory: '%kernel.project_dir%/public/uploads/user/avatar'
    user_avatar_web_path: '/uploads/user/avatar'
    thumbnail_sizes:
        icon:
            width: 32
            height: 32
        small:
            width: 75
            height: 75
        medium:
            width: 125
            height: 125
        large:
            width: 200
            height: 200

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $userAvatarDirectory: '%user_avatar_directory%'
            $userAvatarWebPath: '%user_avatar_web_path%'
            $thumbnailSizes: '%thumbnail_sizes%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    ArmorCMS\:
        resource: '../src/'
        exclude:
            - '../src/User/Entity/'
            - '../src/Article/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    _instanceof:
        # all services implementing the CommandHandlerInterface
        # will be registered on the command.bus bus
        ArmorCMS\Shared\CommandHandler\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        # while those implementing QueryHandlerInterface will be
        # registered on the query.bus bus
        ArmorCMS\Shared\QueryHandler\QueryHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: query.bus }

    Gedmo\Timestampable\TimestampableListener:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_listener, event: 'prePersist' }
            - { name: doctrine.event_listener, event: 'onFlush' }
            - { name: doctrine.event_listener, event: 'loadClassMetadata' }

    Gedmo\Blameable\BlameableListener:
        tags:
            - { name: doctrine.event_listener, event: 'prePersist' }
            - { name: doctrine.event_listener, event: 'onFlush' }
            - { name: doctrine.event_listener, event: 'loadClassMetadata' }

    Gedmo\Translatable\TranslatableListener:
        tags:
            - { name: doctrine.event_listener, event: 'postLoad' }
            - { name: doctrine.event_listener, event: 'postPersist' }
            - { name: doctrine.event_listener, event: 'preFlush' }
            - { name: doctrine.event_listener, event: 'onFlush' }
            - { name: doctrine.event_listener, event: 'loadClassMetadata' }
        calls:
            - [ setDefaultLocale, [ "%default_locale%" ] ]
            - [ setTranslatableLocale, [ "%translatable_locale%" ] ]
            - [ setPersistDefaultLocaleTranslation, [true] ]
            - [ setTranslationFallback, [ false ] ]
